#This is a game where the player have to guess a random number generated by the program. He
import random

guessesTaken = 0 #A counter

print('Hello! What is your name?') # a greeting message from the game
myName = input()#Here the player can input his/her name

number = random.randint(1, 20)#Here the random number is being generated
print('Well, ' + myName + ', I am thinking of a number between 1 and 20.')#The game is informint the player about the rules

while guessesTaken < 6: #The player can guess 6 times totally.
    print('Take a guess.')#messsage from the game 
    guess = input()#a guess from the player
    guess = int(guess)#Converting the input to int

    guessesTaken += 1#adding +1 to the counter.

    if guess < number:#If the player guess is lower than the random number
        print('Your guess is too low.')#informing the player that the guess is too low

    if guess > number:#If the player guess is higher than the random number
        print('Your guess is too high.')#informing the player that the guess is too high

    if guess == number:#if the player guesses the number
        break#breaking out fo the questining loop

if guess == number:#if the number has been guessed
    guessesTaken = str(guessesTaken)#Converting the counter to string
    print('Good job, ' + myName + '! You guessed my number in ' + guessesTaken + ' guesses!')# Informing the player that he won and how many round did it take.

if guess != number:#If the player didn't win under 6 round
    number = str(number)#converting the number to string
    print('Nope. The number I was thinking of was ' + number)#Telling the player what was the number
